//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Business_Logical_Layer.ReportesWS {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_VentasSoap", Namespace="http://tempuri.org/")]
    public partial class WS_Ventas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ResumenMensualPorProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Ventas() {
            this.Url = global::Business_Logical_Layer.Properties.Settings.Default.Business_Logical_Layer_ReportesWS_WS_Ventas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ResumenMensualPorProductoCompletedEventHandler ResumenMensualPorProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ResumenMensualPorProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReporteMensual[] ResumenMensualPorProducto(ReporteMensual[] filas) {
            object[] results = this.Invoke("ResumenMensualPorProducto", new object[] {
                        filas});
            return ((ReporteMensual[])(results[0]));
        }
        
        /// <remarks/>
        public void ResumenMensualPorProductoAsync(ReporteMensual[] filas) {
            this.ResumenMensualPorProductoAsync(filas, null);
        }
        
        /// <remarks/>
        public void ResumenMensualPorProductoAsync(ReporteMensual[] filas, object userState) {
            if ((this.ResumenMensualPorProductoOperationCompleted == null)) {
                this.ResumenMensualPorProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResumenMensualPorProductoOperationCompleted);
            }
            this.InvokeAsync("ResumenMensualPorProducto", new object[] {
                        filas}, this.ResumenMensualPorProductoOperationCompleted, userState);
        }
        
        private void OnResumenMensualPorProductoOperationCompleted(object arg) {
            if ((this.ResumenMensualPorProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResumenMensualPorProductoCompleted(this, new ResumenMensualPorProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReporteMensual {
        
        private int id_PedidoField;
        
        private System.DateTime fechaPedidoField;
        
        private decimal montoEnvioField;
        
        private decimal totalPedidoGuardadoField;
        
        private int id_ProductoField;
        
        private string nombreProductoField;
        
        private decimal subtotalItemField;
        
        private int totalItemsField;
        
        private decimal totalCalculadoField;
        
        /// <remarks/>
        public int Id_Pedido {
            get {
                return this.id_PedidoField;
            }
            set {
                this.id_PedidoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaPedido {
            get {
                return this.fechaPedidoField;
            }
            set {
                this.fechaPedidoField = value;
            }
        }
        
        /// <remarks/>
        public decimal MontoEnvio {
            get {
                return this.montoEnvioField;
            }
            set {
                this.montoEnvioField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalPedidoGuardado {
            get {
                return this.totalPedidoGuardadoField;
            }
            set {
                this.totalPedidoGuardadoField = value;
            }
        }
        
        /// <remarks/>
        public int Id_Producto {
            get {
                return this.id_ProductoField;
            }
            set {
                this.id_ProductoField = value;
            }
        }
        
        /// <remarks/>
        public string NombreProducto {
            get {
                return this.nombreProductoField;
            }
            set {
                this.nombreProductoField = value;
            }
        }
        
        /// <remarks/>
        public decimal SubtotalItem {
            get {
                return this.subtotalItemField;
            }
            set {
                this.subtotalItemField = value;
            }
        }
        
        /// <remarks/>
        public int TotalItems {
            get {
                return this.totalItemsField;
            }
            set {
                this.totalItemsField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalCalculado {
            get {
                return this.totalCalculadoField;
            }
            set {
                this.totalCalculadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ResumenMensualPorProductoCompletedEventHandler(object sender, ResumenMensualPorProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResumenMensualPorProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResumenMensualPorProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReporteMensual[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReporteMensual[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591